services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - "1433:1433"
    networks:
        - mynetwork
    environment:
        - MSSQL_SA_PASSWORD=Password123?
        - ACCEPT_EULA="Y"


  authenticationapp:
    image: ${DOCKER_REGISTRY-}authenticationapp
    container_name: authenticationapp
    build:
      context: .
      dockerfile: AuthenticationApp/Dockerfile
    ports:
        - "5000:80"
    depends_on:
        - database
    networks:
        - mynetwork


networks:
  mynetwork:
    driver: bridge

